name: Screenshot Github Page

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed
jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.0.2
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot-desktop.png
