name: Screenshot Github Page

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed
jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest

    steps:
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ steps.deployment.outputs.page_url }}
          destination: screenshot-desktop.png
